blank_issues_enabled: false
contact_links:
  - name: Preciso de ajuda / tenho uma dúvida
    url: https://github.com/jIDvDIj/slot2sync/discussions
    about: Tire dúvidas, peça suporte e converse com a comunidade.
